Header
thekarinaten/lambda-restaurant pull request #2
Opened 2020-04-17 12:23 UTC by thekarinaten

2020-04-22 14:31 UTC, katsu223 requested changes

2020-04-22 14:31 UTC, katsu223 commented on assets/css/style.css
> +  }
```suggestion
div {
  box-sizing: border-box;
}
```

2020-04-22 14:31 UTC, katsu223 commented on assets/css/style.css
> +  }
```suggestion
}
```

2020-04-22 14:31 UTC, katsu223 commented on assets/css/style.css
> +
```suggestion
```

2020-04-22 14:31 UTC, katsu223 commented on assets/css/style.css
> +  display: flex;
sort alphabetically here and below

2020-04-22 14:31 UTC, katsu223 commented on assets/css/style.css
> +  background-position: 50% 0px;
```suggestion
  background-position: 50% 0;
```

2020-04-22 14:31 UTC, katsu223 commented on assets/css/style.css
> +  color: white;
```suggestion
  color: #fff;
```

2020-04-22 14:31 UTC, katsu223 commented on assets/css/style.css
> +  padding-bottom: 2px;
Something wierd

2020-04-22 14:31 UTC, katsu223 commented on assets/css/style.css
> +  font-family: Yeseva One;
Add more fallback fonts

2020-04-22 14:31 UTC, katsu223 commented on assets/css/style.css
> +}
```suggestion
}

```
Add blank line in the end on the file

2020-04-22 14:31 UTC, katsu223 commented on assets/css/style.css
> +
```suggestion
```

2020-04-22 14:31 UTC, katsu223 commented on assets/images/desktop.ini
> +Layer 1.png=@Layer 1.png,0
What is it? Delete it from the commit

2020-04-22 14:31 UTC, katsu223 commented on index.html
> +    </content>
Fix indent

2020-04-22 14:31 UTC, katsu223 commented on index.html
> +      <h2 class="title">the right ingredients for the right food</h2>
Too common class name

2020-04-22 14:32 UTC, katsu223 commented
Gimme the link to the deploy with it commits

2020-04-22 14:55 UTC, thekarinaten commented on assets/images/desktop.ini
> +Layer 1.png=@Layer 1.png,0
how?

2020-04-25 10:14 UTC, katsu223 requested changes

2020-04-25 10:14 UTC, katsu223 commented on assets/css/style.css
> +  }
you didnt fix it

2020-04-25 10:14 UTC, katsu223 commented on assets/css/style.css
> + list-style: none;
```suggestion
  align-items: center;
  display: flex;
  height: 21px;
  list-style: none;
```

2020-04-25 10:14 UTC, katsu223 commented on assets/images/desktop.ini
> +Layer 1.png=@Layer 1.png,0
Try to google first - then ask me

2020-04-25 10:14 UTC, katsu223 commented on index.html
> +      <content>
Delete this tag

2020-04-25 10:14 UTC, katsu223 commented on index.html
> +        <h2 class="title">the right ingredients for the right food</h2>
```suggestion
        <h3 class="title">the right ingredients for the right food</h3>
```

2020-05-10 20:03 UTC, katsu223 requested changes

2020-05-10 20:03 UTC, katsu223 commented on index.html
> +        </header>
```suggestion
        <nav class="nav-bar">
          <ul class="menu-bar">
            <li class="menu-item">home</li>
            <li class="menu-item">about</li>
            <li class="menu-item">ingredients</li>
            <li class="menu-item">menu</li>
            <li class="menu-item">reviews</li>
            <li class="menu-item">reservations</li>
          </ul>
          <ul class="socials">
            <li class="social-item"><img class="social-image" src="assets/images/twitter.png"></li>
            <li class="social-item"><img class="social-image" src="assets/images/youtube.png"></li>
            <li class="social-item"><img class="social-image" src="assets/images/facebook.png"></li>
          </ul>
        </nav>
      </header>
```

2020-05-17 12:47 UTC, katsu223 requested changes

2020-05-17 12:47 UTC, katsu223 commented on assets/css/style.css
> +  color: #ffffff;
```suggestion
  color: #fff;
```

2020-05-17 12:47 UTC, katsu223 commented on assets/css/style.css
> +  padding: 8px 8px;
```suggestion
  padding: 8px;
```

2020-05-17 12:52 UTC, katsu223 requested changes

2020-05-17 12:52 UTC, katsu223 commented on assets/css/style.css
> +  padding: 8px 8px;
```suggestion
```

2020-05-17 12:52 UTC, katsu223 commented on assets/css/style.css
> +  height: 21px;
```suggestion
```

2020-05-17 12:52 UTC, katsu223 commented on assets/css/style.css
> +  align-items: center;
```suggestion
```

2020-05-17 12:52 UTC, katsu223 commented on assets/css/style.css
> +  align-items: center;
```suggestion
```

2020-05-17 12:52 UTC, katsu223 commented on assets/css/style.css
> +  height: 110px;
```suggestion
```

2020-05-17 12:52 UTC, katsu223 commented on assets/css/style.css
>  }
```suggestion
```

2020-05-17 13:08 UTC, katsu223 approved these changes

2020-05-17 13:08 UTC, merged