About
thekarinaten/lambda-restaurant pull request #4
Opened 2020-05-09 13:59 UTC by thekarinaten

2020-05-17 14:29 UTC, katsu223 requested changes

2020-05-17 14:29 UTC, katsu223 commented on assets/css/style.css
> +  color: rgb(255, 255, 255);
```suggestion
  color: #fff;
```

2020-05-17 14:29 UTC, katsu223 commented on assets/css/style.css
> +  font-family: "Yeseva One";
Fallback font

2020-05-17 14:29 UTC, katsu223 commented on assets/css/style.css
> +  margin: 0px auto;
```suggestion
  margin: 0 auto;
```

2020-06-13 15:47 UTC, katsu223 requested changes

2020-06-13 15:47 UTC, katsu223 commented on assets/css/style.css
> +  color: #cc9900;
```suggestion
  color: #c90;
```

2020-06-13 15:47 UTC, katsu223 commented on assets/css/style.css
> +}
Move to the top of file

2020-06-13 15:47 UTC, katsu223 commented on assets/css/style.css
>  }
Do not use tags for styling, and smth wrong with braces

2020-06-14 12:06 UTC, katsu223 requested changes

2020-06-14 12:06 UTC, katsu223 commented on assets/css/style.css
> +  color: #cc9900;
```suggestion
  color: #c90;
```

2020-06-14 12:06 UTC, katsu223 commented on assets/css/style.css
> +  box-sizing: border-box;
?

2020-06-14 12:06 UTC, katsu223 commented on assets/css/style.css
>  }
Move body below .class slectors

2020-06-14 12:06 UTC, katsu223 commented on assets/css/style.css
> +}
```suggestion
}

```
and place .wrapper under the body

2020-06-14 12:34 UTC, thekarinaten commented on assets/css/style.css
>  }
below or above

2020-07-08 08:01 UTC, katsu223 approved these changes

2020-07-08 08:05 UTC, merged